# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2.4.5.dev0+g77864ff.d20230226'
__version_tuple__ = version_tuple = (2, 4, 5, 'dev0', 'g77864ff.d20230226')
