"""empty message

Revision ID: 4994f94014b5
Revises: 
Create Date: 2024-02-18 10:48:36.261716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4994f94014b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('asset_id', type_='unique')

    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.drop_constraint('check_a_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.create_unique_constraint('check_a_id', ['assetid'])

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_unique_constraint('asset_id', ['id'])

    # ### end Alembic commands ###
