"""empty message

Revision ID: 6e10d0ad5159
Revises: 863f81a1b742
Create Date: 2024-02-27 16:25:21.514371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e10d0ad5159'
down_revision = '863f81a1b742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('globalset', schema=None) as batch_op:
        batch_op.alter_column('settingid',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('globalset', schema=None) as batch_op:
        batch_op.alter_column('settingid',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
